### ISSUE TITLE
I can't compile this lib

### ISSUE THREAD

**Issue by deviderx** [4d/SQLlib_4D#5]
Please how to compile and use this lib

**Comment by miyako** [comment]
did you read https://github.com/4D/SQLlib_4D/tree/master/lib4d_sql ?

it says ``make``. are you unfamiliar with ``make``? 

but given that the files are plain C, it shouldn't be difficult to create a Visual C  or X code project manually.

are you familiar with Visual C or X code?

I am sorry, but you need to put more effort to ask questions in a way that the reader can understand.

**Comment by deviderx** [comment]
Please explain how to use make itry to compile it in visual c++ 2015 but it faild 
Code block give me error on secure methods like strcpy_s it doesn't support it

**Comment by miyako** [comment]
Hi, non-secure methods are just warnings, they don't throw and error unless you explicitly tell the compiler to treat all warnings as errors. You really need to take a step back and learn how to use visual studio and some basic stuff about the visual c language.
